### ISSUE TITLE
Minimium viable product TODOs

### ISSUE THREAD

**Issue by pellaeon** [pellaeon/django-rest-framework-webdav#1]
# Stage 1: read-only WebDAV

- [ ] serializers and fields of WebDAV elements (`to_representation()`)
- [ ] base resource class
- [ ] XML renderer
- [ ] viewset that instantiate a resource object and feeds it into serializer

# Stage 2: read-write WebDAV
- [ ] validators for serializers and fields
- [ ] XML parser
- [ ] viewset write actions

# Stage 3: permission
- [ ] link permission class with resource class
- [ ] survey

# Stage 4: locking
- [ ] survey
- [ ] `Lock` base class (allow different implementations)
- [ ] `ModelLock`: lock implemented with Django models
